### ISSUE TITLE
Unable to bring up nginx after adding the kafka module

### ISSUE THREAD

**Issue by divgwd** [brg-liuwei/ngx_kafka_module#11]
Hi
I tried bringing up  nginx after adding the kafka module but  am getting the below error when I tried testing the config file:
[root@smsc ngx_kafka_module]# /usr/sbin/nginx -t
nginx: [emerg] unknown directive "kafka" in /etc/nginx/nginx.conf:37
nginx: configuration file /etc/nginx/nginx.conf test failed.
my Nginx version is 1.2.4 
RHEL 6.4
attaching my config file as well.
[nginx.txt](https://github.com/brg-liuwei/ngx_kafka_module/files/611301/nginx.txt)

**Comment by brg-liuwei** [comment]
Seems like you hadn't compiled ngx_kafka_module into nginx.

**Comment by divgwd** [comment]
Below is the output 
[root@smsc ~]# ldd /usr/local/nginx/sbin/nginx |grep librdkafka
        librdkafka.so.1 => not found
[root@smsc ~]# locate librdkafka.so.1
/opt/librdkafka/src/librdkafka.so.1
/usr/local/lib/librdkafka.so.1
so I copied the binary to /lib64/
[root@smsc lib64]# cp /usr/local/lib/librdkafka.so.1 .
[root@smsc lib64]# ldd /usr/local/nginx/sbin/nginx |grep librdkafka
        librdkafka.so.1 => /lib64/librdkafka.so.1 (0x00007f64bbb46000)
but even after that when  I restart i get the below error
[root@smsc lib64]# service nginx restart
nginx: [emerg] unknown directive "kafka" in /etc/nginx/nginx.conf:37
nginx: configuration file /etc/nginx/nginx.conf test failed
[root@smsc lib64]#
[root@smsc lib64]#
[root@smsc lib64]# ldd /usr/local/nginx/sbin/nginx |grep librdkafka
        librdkafka.so.1 => /lib64/librdkafka.so.1 (0x00007f3a77c4b000)
[root@smsc lib64]#

**Comment by brg-liuwei** [comment]
seems like you have more than one nginx installed in your system:

`/usr/local/nginx/sbin/nginx` and `/usr/sbin/nginx`, make sure which nginx is used when executing `service nginx restart`. Maybe you should try `/usr/local/nginx/sbin/nginx -t`

**Comment by divgwd** [comment]
Thanks you were right my system has two nginx installed.
I am getting the below error after restarting with the right instance if nginx.
[root@smsc lib64]# service nginx restart
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Stopping nginx:                                            [FAILED]
grep: unrecognized option '--add-module=/opt/ngx_kafka_module'
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
useradd: unrecognized option '--add-module=/opt/ngx_kafka_module'

**Comment by brg-liuwei** [comment]
Oh, it seems like there is something wrong with your service scripts (`/etc/init.d/nginx`)
Please do those operations as follows to check if your nginx is worked:

`sudo killall nginx`
`/usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf -t`
If test ok:
`/usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf`

If it works, It is means that you should fix some errors in `/etc/init.d/nginx`.

**Comment by divgwd** [comment]
Hi,
I am unable to send msgs to kafka via the curl command
curl http://172.16.23.17:8000/alarmdata/kafkatopic/ -d "message send to kafka topic"
[root@smsc ~]# netstat -anlp|grep nginx
tcp        0      0 0.0.0.0:3000                0.0.0.0:*                   LISTEN      24346/nginx
tcp        0      0 0.0.0.0:8000                0.0.0.0:*                   LISTEN      24346/nginx
tcp        0      0 172.16.23.17:38532          172.16.23.15:9092           ESTABLISHED 24347/nginx
unix  3      [ ]         STREAM     CONNECTED     196746843 24346/nginx
unix  3      [ ]         STREAM     CONNECTED     196746842 24346/nginx

Do we have to specify a different port for nginx's kafka module  ??

**Comment by brg-liuwei** [comment]
Oh, It looks like a FAQ, check `config/server.properties` and `nginx.conf` again. 

Make sure the value of `host.name` in `config/server/properties` equals to the hostname of `kafka_broker_list` in `nginx.conf`.

Many users make wrong configuration as follows:

file `config/server.properties`:
`host.name=localhost`

file `nginx.conf`:
`kafka_broker_list: 127.0.0.1:9092`

With this context, kafka could not recv msgs from nginx, because the resolver of kafka cannot resolve `localhost` to `127.0.0.1` successfully.

**Comment by divgwd** [comment]
Finally got it up and running :) 
Thank you :)

**Comment by divgwd** [comment]
Hi,
can we send the data to a particular Id of the kafka topic??

**Comment by brg-liuwei** [comment]
For now, we send data to kafka topic for automatic partitioning using the topic's partitioner function.
However, I think this requirement is rather reasonable. So, I am adding a directive named `kafka_partition` as soon as possiable.
Maybe you will see this feature tomorrow.

**Comment by brg-liuwei** [comment]
> can we send the data to a particular Id of the kafka topic?

@divgwd A new directive `kafka_partition` is added. Does it satisfies your requirement?

**Comment by brg-liuwei** [comment]
Of course you can

**Comment by divgwd** [comment]
so I set  
include /etc/nginx/conf.d/*.conf;
    kafka;

    kafka_broker_list <I.P>:8086 ; # host:port ...


8086 is the port my haproxy is binding to

**Comment by brg-liuwei** [comment]
No, that's wrong, absolutely. The right architecture should be:

        HAProxy -> Nginx -> Kafka

I'm really confused why you set HAProxy on the front of Kafka.

**Comment by divgwd** [comment]
we were pushing netdata's data from the site servers to the local kafka installation we had nginx set up on one of the  site servers which has a public IP which intern routes it to haproxy installation on one of our local servers which has a public IP .

**Comment by brg-liuwei** [comment]
> 8086 is the port my haproxy is binding to

The `kafka_broker_list <port>` set in nginx.conf must be the port kafka is binding to

**Comment by divgwd** [comment]
Thank you!!
I changed the proxy server from HAproxy to Nginx now.
the set up is now
kafka<Nginx_with_kafka<Nginx<list_of_netdata_servers
from
kafka<HAproxy<Nginx_with_kafka<list_of_netdata_servers
