### ISSUE TITLE
Unable to execute ./configure --add-module=/path/to/ngx_kafka_module

### ISSUE THREAD

**Issue by DataEngg** [brg-liuwei/ngx_kafka_module#2]
Hi,

I am unable to execute following command in nginx
./configure --add-module=/Users/kunalgupta/Desktop/Backup/Kunal/Projects/DataScience/ngx_kafka_module

 I am using mac OS X yosemite. I have installed nginx from following url http://www.robertmulley.com/tutorial/nginx-install-and-setup-mac-os-x-yosemite/

Please help me how will i compile your module in nginx directory.

**Comment by brg-liuwei** [comment]
I need more error information
