### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by BraveNewPumpkin** [brg-liuwei/ngx_kafka_module#3]
Please add a license file to the project so users of the code can know if it is legal to use in their software, projects, etc. (and protect yourself from liability).

GitHub has a guide to help choose and add a license: [https://help.github.com/articles/open-source-licensing/](url)

If you would like more information about choosing a license: [http://choosealicense.com/](url)

If it is open source some examples might be:
**Apache** http://choosealicense.com/licenses/apache-2.0/
[swift uses apache 2.0](https://github.com/apple/swift/blob/master/LICENSE.txt)

**MIT** http://choosealicense.com/licenses/mit/
[dotnet core uses MIT license](https://github.com/dotnet/corefx/blob/master/LICENSE)

**Comment by brg-liuwei** [comment]
Thank you very much for your advice

**Comment by davidalber** [comment]
It looks like this should be closed due to 7355ada.
