### ISSUE TITLE
rd_kafka_poll before rd_kafka_destroy

### ISSUE THREAD

**Issue by takaomag** [brg-liuwei/ngx_kafka_module#9]
Hi,

Thank you so much for your cool module!

I have one suggestion about `ngx_http_kafka_exit_worker`.
https://github.com/brg-liuwei/ngx_kafka_module/blob/master/ngx_http_kafka_module.c#L386

In my opinion, `rd_kafka_poll` should be done until `rd_kafka_outq_len(main_conf->rk) > 0`, in order to ensure kafka messages to be delivered before exit.
```c
rd_kafka_poll(main_conf->rk, 0);

while (rd_kafka_outq_len(main_conf->rk) > 0) {
    rd_kafka_poll(main_conf->rk, 100);
}

// TODO: rd_kafka_topic_destroy(each loc conf rkt );
rd_kafka_destroy(main_conf->rk);
```

- C example code in librdkafka repository
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.c#L619

**Comment by brg-liuwei** [comment]
Great!

Would you please commit a pull request?

**Comment by takaomag** [comment]
Thanks and done the pull request.
https://github.com/brg-liuwei/ngx_kafka_module/pull/10
